const GET_DOGS = 'GET_DOGS';
const GET_DOG_BY_NAME = 'GET_DOG_BY_NAME';
const ADD_DOG = 'ADD_DOG';
const REMOVE_DOG = 'REMOVE_DOG';
const FILTER_DOGS = 'FILTER_DOGS';
const FILTER_DOGS_BY_TEMPERAMENTS = 'FILTER_DOGS_BY_TEMPERAMENTS';
const CLEAR_FILTER = 'CLEAR_FILTER';
const ORDER_DOGS_NAME = 'ORDER_DOGS_NAME';
const ORDER_DOGS_WEIGHT = 'ORDER_DOGS_WEIGHT';
const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS';
const ADD_TEMPERAMENT = 'ADD_TEMPERAMENT';
const REMOVE_TEMPERAMENT = 'REMOVE_TEMPERAMENT';
const ORDER_TEMPERAMENTS = 'ORDER_TEMPERAMENTS';

module.exports = {
    GET_DOGS,
    GET_DOG_BY_NAME,
    ADD_DOG,
    REMOVE_DOG,
    FILTER_DOGS,
    FILTER_DOGS_BY_TEMPERAMENTS,
    CLEAR_FILTER,
    ORDER_DOGS_NAME,
    ORDER_DOGS_WEIGHT,
    GET_TEMPERAMENTS,
    ADD_TEMPERAMENT,
    REMOVE_TEMPERAMENT,
    ORDER_TEMPERAMENTS
}