const GET_DOGS = 'GET_DOGS';
const GET_DOG = 'GET_DOG';
const ADD_DOG = 'ADD_DOG';
const REMOVE_DOG = 'REMOVE_DOG';
const FILTER_DOGS = 'FILTER_DOGS';
const CLEAR_FILTER = 'CLEAR_FILTER';
const ORDER_DOGS_NAME = 'ORDER_DOGS_NAME';
const ORDER_DOGS_WEIGHT = 'ORDER_DOGS_WEIGHT';

module.exports = {
    GET_DOGS,
    ADD_DOG,
    REMOVE_DOG,
    FILTER_DOGS,
    CLEAR_FILTER,
    ORDER_DOGS_NAME,
    ORDER_DOGS_WEIGHT
}